"""Adiciona data_compra ao ativo

Revision ID: 91a509097704
Revises: c5775801318e
Create Date: 2025-04-10 11:24:24.168178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91a509097704'
down_revision = 'c5775801318e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crypto_asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_compra', sa.Date(), nullable=False))
        batch_op.drop_column('preco_medio')
        batch_op.drop_column('lucro_prejuizo')
        batch_op.drop_column('preco_atual')
        batch_op.drop_column('variacao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crypto_asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variacao', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('preco_atual', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('lucro_prejuizo', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('preco_medio', sa.FLOAT(), nullable=True))
        batch_op.drop_column('data_compra')

    # ### end Alembic commands ###
