"""init

Revision ID: c5775801318e
Revises: 
Create Date: 2025-04-09 13:07:51.096422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5775801318e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_id', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('crypto_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=True),
    sa.Column('valor_pago', sa.Float(), nullable=True),
    sa.Column('preco_atual', sa.Float(), nullable=True),
    sa.Column('variacao', sa.Float(), nullable=True),
    sa.Column('lucro_prejuizo', sa.Float(), nullable=True),
    sa.Column('preco_medio', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crypto_asset')
    op.drop_table('user')
    # ### end Alembic commands ###
